### ISSUE TITLE
incompréhension de la documentation

### ISSUE THREAD

**Issue by landryyrdnal** [HelloAsso/helloasso-python#8]
Bonjour,
dans la documentation je ne comprends pas ce passage : 
"Dirigez l'utilisateur vers l'url présente dans full_url, il lui sera demandé de valider l'autorisation. Un callback sera alors effectué vers la redirect_url renseignée."
Je suis novice dans le travail avec les api et je n'arrive vraiment pas à comprendre cette étape, serait-il possible de développer un peu plus la documentation sur ce passage ? par un exemple peut-être ou par une description plus poussée de l'étape.

Merci d'avance,

**Comment by mgi-dev** [comment]
Bonjour,

Ce point de la documentation ne concerne que les partenaires HelloAsso, vous ne pourrez pas utiliser cette fonctionnalité si vous n'êtes pas partenaire.

La documentation a été mise à jour pour clarifier ce point.

L'implémentation de cette fonctionnalité est très dépendante du Framework utilisé, son usage n'est donc pas détailé.
Mais il est vrai qu'un exemple serait le bienvenu.
